language: cpp
compiler:
  - gcc
  - i586-mingw32msvc-gcc
  - clang
before_install:
  - git submodule update --init
  - yes | sudo add-apt-repository ppa:mapnik/boost
  - sudo apt-get update
install: sudo apt-get install libicu-dev boost1.49 libboost-chrono1.49-dev libboost-filesystem1.49-dev libboost-program-options1.49-dev libboost-system1.49-dev libboost-thread1.49-dev gcc-mingw-w64 g++-mingw-w64
script: autoreconf -i && ./configure && make -j2 check
